name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 12 Pro']
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        set -o pipefail && \
        xcodebuild -project Currency.xcodeproj \
        -scheme Currency \
        -destination "${destination}" \
        test | xcpretty
      env:
        destination: ${{ matrix.destination }}
